name: JsonReadTest

on:
  workflow_dispatch:

jobs:
  read:
    runs-on: ubuntu-latest
    outputs:
      prop: ${{steps.prepare_json.outputs.prop}}
      json: ${{steps.prepare_json.outputs.json}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: prepare_json
        name: Prepare Json
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "json<<$EOF" >> $GITHUB_OUTPUT
          cat multiLineJson.json >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
          echo "$GITHUB_OUTPUT"
          echo "${{steps.prepare_json.outputs}}"
      - run: |
          echo "${{fromJson(steps.prepare_json.outputs.json).propA}}"
          echo "${{fromJson(steps.prepare_json.outputs.json).propB}}"
          cond="${{fromJson(steps.prepare_json.outputs.json).propA}}"
          msg="${{fromJson(steps.prepare_json.outputs.json).propB}}"
          echo $msg
          echo $cond
          echo "prop=$msg"
          echo "prop<<$EOF" >> $GITHUB_OUTPUT
          echo $msg >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
          echo "${{steps.prepare_json.outputs.prop}}"

  use:
    runs-on: ubuntu-latest
    needs: read
    steps:
      - name: Echo Json values
        run: |
          echo "${{needs.read.outputs.json}}"
          echo "${{needs.read.outputs.prop}}"

      - name: Should run
        if: fromJson(needs.read.outputs.json).propA == true
        run: echo "should run here!"

      - name: Should not run
        if: fromJson(needs.read.outputs.json).propA != true
        env:
          COND: ${{fromJson(needs.read.outputs.json).propA}}
        run: |
          echo "$COND"
          exit 1
