name: JsonReadTest

on:
  workflow_dispatch:

jobs:
  read:
    runs-on: ubuntu-latest
    outputs:
      json: ${{steps.prepare_json.outputs.json}}
      prop: ${{steps.prepare_json.outputs.prop}}
      cond: ${{steps.prepare_json.outputs.cond}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: prepare_json
        name: Prepare Json
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "json<<$EOF" >> $GITHUB_OUTPUT
          cat multiLineJson.json >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
          echo "$GITHUB_OUTPUT"
          echo "${{steps.prepare_json.outputs}}"
      - run: |
          echo "${{fromJson(steps.prepare_json.outputs.json).propA}}"
          echo "${{fromJson(steps.prepare_json.outputs.json).propB}}"
          prop="${{fromJson(steps.prepare_json.outputs.json).propA}}"
          cond="${{fromJson(steps.prepare_json.outputs.json).propB}}"
          echo "prop=$prop" >> "$GITHUB_OUTPUT"
          echo "cond=$cond" >> "$GITHUB_OUTPUT"

  use:
    runs-on: ubuntu-latest
    needs: read
    steps:
      - name: Echo Json values
        run: |
          echo "${{needs.read.outputs.json}}"
          echo "${{needs.read.outputs.prop}}"
          echo "${{needs.read.outputs.cond}}"

      - name: Should run
        if: needs.read.outputs.cond == true
        run: echo "should out here!"

      - name: Should run too
        if: needs.read.outputs.cond == true
        run: echo "should out here!"

      - name: Should not run
        if: needs.read.outputs.cond != true
        env:
          PROP: ${{needs.read.outputs.prop}}
          COND: ${{needs.read.outputs.cond}}
        run: |
          echo "$PROP $COND"
          exit 1
